import type { Metadata } from "next";
import "./globals.css";
import { marklMono } from "../lib/fonts";
import { ethosNova } from "../lib/fonts";
import ClientWrapper from "@/components/sections/ClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${marklMono.variable} ${ethosNova.variable}`}>
      <body
        className="antialiased bg-brand-black"
      >
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
