import type { Metadata } from "next";
import "./globals.css";
import { marklMono } from "../lib/fonts";
import { ethosNova } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${marklMono.variable} ${ethosNova.variable}`}>
      <body
        className="antialiased bg-brand-black relative"
      >
        {children}
        <aside className="absolute top-0 left-0 text-h2 text-[#8D98B3] text-[12px] leading-[150%] tracking-[0.02em] w-[20vw] ml-[1vw] mt-[1vw]">
          current version is still very MVP, currently iterating day-by-day 🫡
        </aside>
      </body>
    </html>
  );
}
