import type { Metadata } from "next";
import "./globals.css";
import { marklMono } from "../lib/fonts";
import { ethosNova } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${marklMono.variable} ${ethosNova.variable}`}>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
